services:
  - type: web
    name: backga-laravel
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan migrate --force
      php artisan storage:link
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    region: oregon
    branch: main
    rootDir: .
    autoDeploy: true
